### ISSUE TITLE
Porterbuddy orders are sometimes not created

### ISSUE THREAD

**Issue by andersem** [Dintero/Dintero.Checkout.WooCommerce.V2#103] opened 2022-09-22 09:15 UTC
Merchant reports that for some orders, Porterbuddy orders are not always placed after completing the order.

Examples:

| transaction id         | paid time                | capture time             | payment method |                       
|------------------------|--------------------------|--------------------------|----------------|
| 5cJVBXdUsiJT6wixXNsQbn | 2022-08-30T09:52:40.891Z | 2022-08-31T10:59:46.450Z | Card           |
| 5cLhfnA65uUQw8tmRTR8LC | 2022-09-06T08:10:01.551Z | 2022-09-06T11:08:21.123Z | Vipps          |

There are at least a couple of these each week.

Versions: Porterbuddy plugin 0.5.4, laget av Maksimer
Dintero plugin: 1.2.0

Internal Slack link: https://dintero.slack.com/archives/C8FD6AQJ1/p1662640051745919

We can share more details in other channels.

**Comment by jakobjolstad** [comment] 2022-10-03 12:25
Link to Porterbuddy ZIP file: https://drive.google.com/file/d/1QYeJQxvF_hbKWcdi5FRCYuoMFRe6OrM_/view

**Comment by jakobjolstad** [comment] 2022-10-03 12:25
[dintero-checkout-for-woocommerce-2022-09-06-8476d40ba71c7f6eb58fa2c246c41e50.log (1).txt](https://github.com/Dintero/Dintero.Checkout.WooCommerce.V2/files/9697429/
[porterbuddy-log-2022-09-06-3d73154530983697654c1d48182491fe (1).txt](https://github.com/Dintero/Dintero.Checkout.WooCommerce.V2/files/9697431/porterbuddy-log-2022-09-06-3d73154530983697654c1d48182491fe.1.txt)
dintero-checkout-for-woocommerce-2022-09-06-8476d40ba71c7f6eb58fa2c246c41e50.log.1.txt)

**Comment by jakobjolstad** [comment] 2022-10-03 12:26
[porterbuddy-log-2022-09-06-3d73154530983697654c1d48182491fe (1).txt](https://github.com/Dintero/Dintero.Checkout.WooCommerce.V2/files/9697437/porterbuddy-log-2022-09-06-3d73154530983697654c1d48182491fe.1.txt)

**Comment by jakobjolstad** [comment] 2022-10-03 12:26
[dintero-checkout-for-woocommerce-2022-09-06-8476d40ba71c7f6eb58fa2c246c41e50.log (1).txt](https://github.com/Dintero/Dintero.Checkout.WooCommerce.V2/files/9697440/dintero-checkout-for-woocommerce-2022-09-06-8476d40ba71c7f6eb58fa2c246c41e50.log.1.txt)

**Comment by jakobjolstad** [comment] 2022-10-04 08:17
New internal Slack link: https://dintero.slack.com/archives/C02TVV8PMFB/p1664871417826649

**Comment by mntzrr** [comment] 2022-10-20 09:19
The issue turned out to be caused by the Porterbuddy plugin itself. I am therefore closing this.

**Closed by mntzrr** 2022-10-20 09:19 UTC
Labels: bug
